[package]
name = "cargo-raze"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@google.com>"]
readme = "README.md"
keywords = ["subcommand"]
license = "Apache-2.0"
repository = "https://github.com/google/cargo-raze"
description = """
A Cargo subcommand to generate Bazel BUILD files
"""

[badges]
travis-ci = { repository = "google/cargo-raze", branch = "master" }

[dependencies]
rustc-serialize = "0.3"
cargo = "0.20.0"
itertools = "0.6.0"
slug = "0.1.2"
tera = "0.11.0-beta.4"
serde_derive = "1.0.11"
serde = "1.0.11"
toml = "0.4.4"
serde_json = "1.0"
tempdir = "0.3.5"

[dev-dependencies]
lazy_static = "0.2.8"
hamcrest = "0.1.3"
