[package]
name = "cargo-raze"
version = "0.1.3"
authors = ["Alex McArther <acmcarther@google.com>"]
readme = "README.md"
keywords = ["subcommand"]
license = "Apache-2.0"
repository = "https://github.com/google/cargo-raze"
description = """
A Cargo subcommand to generate Bazel BUILD files
"""

[badges]
travis-ci = { repository = "google/cargo-raze", branch = "master" }

[dependencies]
failure = "0.1.2"
docopt = "1.0.1"
cargo = "0.30.0"
itertools = "0.7.8"
slug = "0.1.4"
tera = "0.11.18"
serde_derive = "1.0.80"
serde = "1.0.80"
toml = "0.4.8"
serde_json = "1.0.32"
tempdir = "0.3.7"

[dev-dependencies]
lazy_static = "1.1.0"
hamcrest = "0.1.3"
