[package]
name = "cargo-raze"
version = "0.3.8"
authors = ["Alex McArther <acmcarther@google.com>"]
readme = "README.md"
keywords = ["subcommand"]
license = "Apache-2.0"
repository = "https://github.com/google/cargo-raze"
edition = "2018"
description = """
A Cargo subcommand to generate Bazel BUILD files
"""

[badges]
travis-ci = { repository = "google/cargo-raze", branch = "master" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "cargo-raze"
path = "src/bin/cargo-raze.rs"

[dependencies]
anyhow = "1.0.30"
docopt = "1.0.2"
cargo-lock = "4.0.1"
cargo-platform = "0.1.0"
cargo_metadata = "0.9.1"
itertools = "0.8.0"
slug = "0.1.4"
tera = "1.0.0"
semver = { version = "0.9.0", features = ["serde"] }
serde_derive = "1.0.84"
serde = "1.0.84"
toml = "0.4.10"
serde_json = "1.0.34"
tempdir = "0.3.7"
spdx = "0.3.4"

[dev-dependencies]
lazy_static = "1.2.0"
hamcrest2 = "0.3.0"
